
1. https://labs.openai.com

Homework: sign up yourself for Dall.E AI service, and produce some interesting pictures and share with the class.
2. Please use array to write a python program to calculate 
1 + 3 + 5 + 7 + .... + 99 + 101. Basically you needa way to create odd number sequence, also creat an array and put the numbers in the array then do the calculation.
3. Now we have learned how to simulate dice rolling. Run the program 4_simple_dice_array.py we have written and posted in our GitHUB site, and see how can modify these programs for your creative ideas and please have fun.
